

/*
 * Author: Tomi Jylhä-Ollila, Finland 2015-2019
 *
 * This file is part of Kunquat.
 *
 * CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
 *
 * To the extent possible under law, Kunquat Affirmers have waived all
 * copyright and related or neighboring rights to Kunquat.
 */


#ifndef KQT_LIMIT_INT
#error "KQT_LIMIT_INT(..) is not defined"
#endif

#ifndef KQT_LIMIT_STRING
#error "KQT_LIMIT_STRING(..) is not defined"
#endif


KQT_LIMIT_INT(HANDLES_MAX)
KQT_LIMIT_INT(KEY_LENGTH_MAX)
KQT_LIMIT_INT(AUDIO_BUFFER_SIZE_MAX)
KQT_LIMIT_INT(THREADS_MAX)
KQT_LIMIT_INT(CALC_DURATION_MAX)
KQT_LIMIT_INT(VOICES_MAX)
KQT_LIMIT_INT(SONGS_MAX)
KQT_LIMIT_INT(TRACKS_MAX)
KQT_LIMIT_INT(SYSTEMS_MAX)
KQT_LIMIT_INT(PATTERNS_MAX)
KQT_LIMIT_INT(PAT_INSTANCES_MAX)
KQT_LIMIT_INT(COLUMNS_MAX)
KQT_LIMIT_INT(CHANNELS_MAX)
KQT_LIMIT_INT(TSTAMP_BEAT)
KQT_LIMIT_INT(TEMPO_SLIDE_SLICE_LEN)
KQT_LIMIT_INT(AUDIO_UNITS_MAX)
KQT_LIMIT_INT(CONTROLS_MAX)
KQT_LIMIT_INT(PROCESSORS_MAX)
KQT_LIMIT_INT(DEVICE_PORTS_MAX)
KQT_LIMIT_INT(HITS_MAX)
KQT_LIMIT_INT(EVENT_NAME_MAX)
KQT_LIMIT_INT(VAR_NAME_MAX)
KQT_LIMIT_INT(DEVICE_EVENT_NAME_MAX)
KQT_LIMIT_INT(TUNING_TABLES_MAX)
KQT_LIMIT_INT(TUNING_TABLE_NOTES_MAX)
KQT_LIMIT_INT(TUNING_TABLE_OCTAVES)

KQT_LIMIT_STRING(DEVICE_EVENT_CHARS)


#undef KQT_LIMIT_INT
#undef KQT_LIMIT_STRING


