# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2010
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat.


import glob


Import('env')

Export('env')

if env['enable_tests']:
    SConscript('test/SConscript')

env_lib = env.Clone()

if not env_lib.GetOption('clean') and 'check' in env['LIBS']:
    env_lib['LIBS'].remove('check')

#print 'lib: ' + env_lib.Dump('LIBS')

env_lib.Append(CPPPATH = ['#/src/lib',
                          '#/src/lib/events',
                          '#/src/lib/generators',
                          '#/src/include'])


env_lib.sources = glob.glob('*.c')

Export('env_lib')

SConscript('events/SConscript')
SConscript('generators/SConscript')

libkunquat = env_lib.SharedLibrary('kunquat', env_lib.sources)
# For some reason, SCons sets the mode to 0755 by default
env_lib.AddPostAction(libkunquat, Chmod(libkunquat[0].abspath, 0644))
env_lib.InstallCreatePath(env_lib['prefix'] + '/lib', libkunquat)


