# coding=utf-8


# Copyright 2009 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


import glob


Import('env')

Export('env')

if env['enable_tests']:
    SConscript('test/SConscript')

env_lib = env.Clone()

if not env_lib.GetOption('clean') and 'check' in env['LIBS']:
    env_lib['LIBS'].remove('check')

#print 'lib: ' + env_lib.Dump('LIBS')

env_lib.Append(CPPPATH = ['#/src/lib',
                          '#/src/lib/events',
                          '#/src/lib/generators',
                          '#/src/include'])


env_lib.sources = glob.glob('*.c')

Export('env_lib')

SConscript('events/SConscript')
SConscript('generators/SConscript')

libkunquat = env_lib.SharedLibrary('kunquat', env_lib.sources)
env_lib.Install(env_lib['prefix'] + '/lib', libkunquat)


