.TH kunquat\-export 1 "2017\-01\-27" "" "Kunquat"

.SH NAME
kunquat\-export \- convert Kunquat compositions into waveform audio

.SH SYNOPSIS
.B kunquat\-export
[
.B \-h
|
.B \-\-version
]
.br
.B kunquat\-export
[
.B \-q
]
[
.B \-o
.I out
]
[
.B \-f
.I fmt
]
[
.B \-b
.I b
]
[
.B \-\-float
]
[
.B \-r
.I n
]
[
.B \-t
.I n
]
[
.B \-\-threads
.I n
]
.I file
[
.I file
.B ...
]

.SH DESCRIPTION
.B kunquat\-export
is a command\-line tool for converting Kunquat compositions into waveform
audio. Kunquat compositions normally have the .kqt suffix.

.SH OPTIONS

.IP "\fB\-o\fR \fIout\fR, \fB\-\-output\fR \fIout\fR"
Write the output into the file \fIout\fR. By default,
.B kunquat\-export
selects the output file format based on the file extension if it is supported.
The default file format is wav.

.IP "\fB\-f\fR \fIfmt\fR, \fB\-\-format\fR \fIfmt\fR"
Write the output file in the format \fIfmt\fR. Run
.B kunquat-export \-h
to see which output formats are supported.

.IP "\fB\-b\fR \fIb\fR, \fB\-\-bits\fR \fIb\fR"
Use \fIb\fR-bit fixed-point format. \fIb\fR is 8, 16, 24 or 32. Default value
is 16.

.IP "\fB\-\-float\fR"
Use floating-point format. Default is fixed-point. This option overrides
\fB-b\fR and forces a 32-bit format.

.IP "\fB\-r\fR \fIn\fR, \fB\-\-rate\fR \fIn\fR"
Mix \fIn\fR frames per second. This will limit the highest frequency in the
sound to \fIn\fR/2 Hz. \fIn\fR is a value between 1000 and 384000. Default
value is 48000.

.IP "\fB\-t\fR \fIn\fR, \fB\-\-track\fR \fIn\fR"
Render the track \fIn\fR. \fIn\fR is a value between 0 and 255 or
\fIall\fR which renders all the existing tracks in order.

.IP "\fB\-\-threads\fR \fIn\fR"
Use \fIn\fR threads for audio rendering. \fIn\fR is a value between 1 and 32.
Default value is 1. Note that while using several threads may improve writing
speed, the resulting output will not be bit-by-bit consistent due to the
non-deterministic order in which notes are mixed together.

.IP "\fB\-h\fR, \fB\-\-help\fR"
Show help and exit.

.IP "\fB\-q\fR, \fB\-\-quiet\fR"
Disable status information. Only error messages will be displayed.

.IP "\fB\-\-version\fR"
Show version and copyright information and exit.

.SH AUTHOR
Written by Tomi Jylhä\-Ollila.


