# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2010
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat waivers have waived all
# copyright and related or neighboring rights to Kunquat. This work
# is published from Finland.


import glob


Import('env')

env_p = env.Clone()

env_p.Append(CPPPATH = ['#/src/include', '#/src/export'])

env_p.Append(LIBPATH = ['#/src/lib'])
env_p.Append(LIBS = ['kunquat'])

player = env_p.Program('kunquat-export', glob.glob('*.c'))
env_p.InstallCreatePath(env_p['prefix'] + '/bin', player)
env_p.InstallCreatePath(env_p['prefix'] + '/share/man/man1', 'kunquat-export.1')


