# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2010
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat waivers have waived all
# copyright and related or neighboring rights to Kunquat. This work
# is published from Finland.


import glob


Import('env_lib')


env_lib.sources += ['events/' + path for path in glob.glob('*.c')]


