

Import('env', 'opts')

env_test = env.Clone()

env_test.Append(CPPPATH = ['#/src/core'])
env_test.Append(LIBPATH = ['#/src/core'])
env_test.Append(LIBS = ['core'])

real = env_test.Program('real', ['real.c'])
env_test.AddPostAction(real, real[0].abspath)

note_table = env_test.Program('note_table', ['note_table.c'])
env_test.AddPostAction(note_table, note_table[0].abspath)
Depends(note_table, 'real')

reltime = env_test.Program('reltime', ['reltime.c'])
env_test.AddPostAction(reltime, reltime[0].abspath)


