.TH kunquat\-player 1 "2016\-11\-14" "" "Kunquat"

.SH NAME
kunquat\-player \- play Kunquat compositions

.SH SYNOPSIS
.B kunquat\-player
[
.B \-h
|
.B \-\-version
]
.br
.B kunquat\-player
[
.B \-q
]
[
.B \-\-buffer\-size
.I n
]
[
.B \-r
.I n
]
[
.B \-t
.I n
]
[
.B \-\-threads
.I n
]
.I file
[
.I file
.B ...
]

.SH DESCRIPTION
.B kunquat\-player
is a command\-line player for playing Kunquat compositions. These files
normally have the .kqt suffix (and additional .gz or .bz2 suffix if the file
is compressed with \fBgzip\fR(1) or \fBbzip2\fR(1)).

.SH OPTIONS

.IP "\fB\-\-buffer\-size\fR \fIn\fR"
Use audio buffer size of \fIn\fR frames. \fIn\fR is a value between 64 and
262144.

.IP "\fB\-r\fR \fIn\fR, \fB\-\-rate\fR \fIn\fR"
Mix \fIn\fR frames per second. This will limit the highest frequency in the
sound to \fIn\fR/2 Hz. \fIn\fR is a value between 2000 and 192000. Default
value is 48000.

.IP "\fB\-t\fR \fIn\fR, \fB\-\-track\fR \fIn\fR"
Play the track \fIn\fR. \fIn\fR is a value between 0 and 255 or \fIall\fR
which plays all the existing tracks in order.

.IP "\fB\-h\fR, \fB\-\-help\fR"
Show help and exit.

.IP "\fB\-q\fR, \fB\-\-quiet\fR"
Disable status information and interactive keys. Only error messages will be
displayed. The only way for the user to stop the playback is via a signal
(e.g. by pressing Ctl+C).

.IP "\fB\-\-threads\fR \fIn\fR"
Use \fIn\fR threads for audio rendering. \fIn\fR is a value between 1 and 32.
Default value is based on the detected number of CPUs in the system.

.IP "\fB\-\-version\fR"
Show version and copyright information and exit.

.SH INTERACTIVE KEYS

If run without the
.B \-q
option,
.B kunquat\-player
supports interactive playback control. The following keys are supported:

.IP "\fBh\fR"
Show the list of interactive keys.

.IP "\fBSpace\fR"
Pause or resume playback.

.IP "\fBLeft\fR"
Seek backwards 10 seconds.

.IP "\fBRight\fR"
Seek forwards 10 seconds.

.IP "\fB[0-9]\fR, \fBa\fR"
Select a track to be played (\fBa\fR plays all tracks).

.IP "\fBp\fR"
Select previous track.

.IP "\fBn\fR"
Select next track.

.IP "\fBBackspace\fR"
Select previous file.

.IP "\fBReturn\fR"
Select next file.

.IP "\fBq\fR"
Quit the player.

.SH AUTHOR
Written by Tomi Jylhä\-Ollila.


