# coding=utf-8


# Copyright 2009 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


Import('env')

env_l = env.Clone()

env_l.Append(CPPPATH = ['#/src/core'])

env_l.Append(LIBPATH = ['#/src/core'])
env_l.Append(LIBS = ['core'])

files = [
    'demo.c',
    'demo_song.c',
]

if env['with_jack']:
    files += ['Audio_jack.c']
if env['with_ao']:
    files += ['Audio_ao.c']
if env['with_openal']:
    files += ['Audio_openal.c']

env_l.Program('demo', files)


