# coding=utf-8

#
# Author: Tomi Jylhä-Ollila, Finland 2010-2013
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat.
#

import os.path

import SCons.Node.FS


Import('env')

env_demo = env.Clone()

tar_cmd = 'tar cj --format=ustar -f ${TARGET.file} ${SOURCE.file}'

ins_target = '../share/kunquat/instruments/'
ins_cmd = (tar_cmd + '; mkdir -p ' + ins_target +
    '; cp ${TARGET.file} ' + ins_target)

files = [
    'example.kqt.bz2',
    'example_ins.kqti.bz2',
    'example_effect.kqte.bz2',
    'example_scale.kqts.bz2',
]

env_demo.Command(files[0], 'kqtc00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[1], 'kqti00', ins_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[2], 'kqte00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[3], 'kqts00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)


doc_kunquat_path = os.path.join(env_demo['prefix'], 'share', 'doc', 'kunquat')
examples_path = os.path.join(doc_kunquat_path, 'examples')

installed = env_demo.InstallCreatePath(examples_path, files)
env_demo.Clean(installed, [examples_path, doc_kunquat_path])


