# coding=utf-8


# Copyright 2010 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


import SCons.Node.FS


Import('env')

env_demo = env.Clone()

tar_cmd = 'tar cj --format=ustar -f ${TARGET.file} ${SOURCE.file}'

files = [
    'example.kqt.bz2',
    'example_ins.kqti.bz2',
    'example_scale.kqts.bz2',
]

env_demo.Command(files[0], 'kunquatc00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[1], 'kunquati00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[2], 'kunquats00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)


doc_kunquat_path = env_demo['prefix'] + '/share/doc/kunquat'
examples_path = doc_kunquat_path + '/examples'

installed = env_demo.InstallCreatePath(examples_path, files)
env_demo.Clean(installed, [examples_path, doc_kunquat_path])


