# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2010
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat waivers have waived all
# copyright and related or neighboring rights to Kunquat. This work
# is published from Finland.


import SCons.Node.FS


Import('env')

env_demo = env.Clone()

tar_cmd = 'tar cj --format=ustar -f ${TARGET.file} ${SOURCE.file}'

files = [
    'example.kqt.bz2',
    'example_ins.kqti.bz2',
    'example_scale.kqts.bz2',
]

env_demo.Command(files[0], 'kunquatc00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[1], 'kunquati00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)

env_demo.Command(files[2], 'kunquats00', tar_cmd,
                 chdir=1, source_scanner=DirScanner)


doc_kunquat_path = env_demo['prefix'] + '/share/doc/kunquat'
examples_path = doc_kunquat_path + '/examples'

installed = env_demo.InstallCreatePath(examples_path, files)
env_demo.Clean(installed, [examples_path, doc_kunquat_path])


