# coding=utf-8


# Copyright 2009 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


import glob


Import('env')

env_p = env.Clone()

env_p.Append(CPPPATH = ['#/src/include', '#/src/audio', '#/src/player'])

env_p.Append(LIBPATH = ['#/src/lib', '#/src/audio'])
env_p.Append(LIBS = ['kunquat', 'audio'])

player = env_p.Program('kunquat-player', glob.glob('*.c'))
env_p.Install(env_p['prefix'] + '/bin', player)
env_p.Install(env_p['prefix'] + '/man/man1', 'kunquat-player.1')


