# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2010
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat.


Import('env')

env_a = env.Clone()

env_a.Append(CPPPATH = ['#/src/lib', '#/src/include', '#/src/audio'])

files = [
    'Audio.c',
    'Audio_creator.c',
    'Audio_null.c',
    'Mix_state.c',
]

if env_a['with_pulse']:
    files += ['Audio_pulse.c']
if env_a['with_jack']:
    files += ['Audio_jack.c']
if env_a['with_openal']:
    files += ['Audio_openal.c']

env_a.StaticLibrary('audio', files)


