# coding=utf-8

#
# Author: Tomi Jylhä-Ollila, Finland 2013
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat.
#

import os.path


Import('env')

env_share = env.Clone()

share_path = os.path.join(env_share['prefix'], 'share')

installed = env_share.InstallCreatePath(share_path, 'icons')


