# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2012
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat.


import glob
import os.path


Import('env')

env_tc = env.Clone()

env_tc.Append(CPPPATH = ['.', '#/src/include'])

env_tc.Append(LIBPATH = ['#/src/lib'])
env_tc.Append(LIBS = ['kunquat', 'check'])


env_tc.sources = glob.glob('*.c')

env_tc.StaticLibrary('test_common', env_tc.sources)


