

Import('env', 'opts')

Export('env', 'opts')

if opts['unit_tests']:
	SConscript('test/SConscript')

#print 'core: ' + env.Dump('LIBS')

env.Append(CPPPATH = ['#/src/core'])

files = [
'Real.c',
'Note_table.c',
]

env.StaticLibrary('core', files)


