# coding=utf-8


# Copyright 2008 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


Import('env', 'opts')

Export('env', 'opts')

if opts['unit_tests']:
	SConscript('test/SConscript')

#print 'core: ' + env.Dump('LIBS')

env.Append(CPPPATH = ['#/src/core'])

files = [
'Real.c',
'Note_table.c',
'Reltime.c',
'Event.c',
'Event_queue.c',
]

env.StaticLibrary('core', files)


