# coding=utf-8


# Copyright 2009 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


Import('env')

Export('env')

if env['enable_tests']:
    SConscript('test/SConscript')

#print 'core: ' + env.Dump('LIBS')

env.Append(CPPPATH = ['#/src/core'])

files = [
    'Real.c',
    'Note_table.c',
    'Reltime.c',
    'Event.c',
    'Event_queue.c',
    'Voice_state.c',
    'Envelope.c',
    'Instrument.c',
    'Instrument_debug.c',
    'Instrument_sine.c',
    'Instrument_pcm.c',
    'File_wavpack.c',
    'Sample.c',
    'Etable.c',
    'Ins_table.c',
    'Voice.c',
    'Voice_pool.c',
    'AAtree.c',
    'Column.c',
    'Channel.c',
    'Order.c',
    'Pat_table.c',
    'Pattern.c',
    'Song.c',
    'Playdata.c',
    'Player.c',
    'Playlist.c',
]

if env['with_jack']:
    files += ['Driver_jack.c']

if env['with_ao']:
    files += ['Driver_ao.c']

if env['with_alsa']:
    files += ['Driver_alsa.c']

env.StaticLibrary('core', files)


