#!/usr/bin/env python3


import multiprocessing
import sys

from kunquat.tracker.tracker import main


if __name__ == '__main__':
    if sys.platform.startswith('darwin'):
        multiprocessing.set_start_method('spawn')
    main()


