# coding=utf-8


# Author: Tomi Jylhä-Ollila, Finland 2010
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat. This work
# is published from various territories.


import glob


Import('env')

env_head = env.Clone()

include_path = env_head['prefix'] + '/include/kunquat'

files = glob.glob('*.h')

ih = env_head.InstallCreatePath(include_path, files)
env_head.Clean(ih, include_path)


