# coding=utf-8


# Copyright 2010 Tomi Jylhä-Ollila
#
# This file is part of Kunquat.
#
# Kunquat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kunquat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kunquat.  If not, see <http://www.gnu.org/licenses/>.


Import('env')

Export('env')

if env['enable_libkunquat']:
    SConscript('lib/SConscript')

if not env.GetOption('clean') and 'check' in env['LIBS']:
    env['LIBS'].remove('check')

if env['enable_libkunquat_dev']:
    SConscript('include/SConscript')

if env['enable_player']:
    SConscript('audio/SConscript')
    SConscript('player/SConscript')

if env['enable_export']:
    SConscript('export/SConscript')

#print 'src: ' + env.Dump('LIBS')


