# coding=utf-8

#
# Author: Tomi Jylhä-Ollila, Finland 2010-2012
#
# This file is part of Kunquat.
#
# CC0 1.0 Universal, http://creativecommons.org/publicdomain/zero/1.0/
#
# To the extent possible under law, Kunquat Affirmers have waived all
# copyright and related or neighboring rights to Kunquat.
#

Import('env')

Export('env')

if env['enable_libkunquat']:
    SConscript('lib/SConscript')

if not env.GetOption('clean') and 'check' in env['LIBS']:
    env['LIBS'].remove('check')

if env['enable_libkunquat_dev']:
    SConscript('include/SConscript')

#print 'src: ' + env.Dump('LIBS')


