

Import('env', 'opts')

Export('env', 'opts')

SConscript('core/SConscript')


if not env.GetOption('clean') and 'check' in env['LIBS']:
	env['LIBS'].remove('check')

#print 'src: ' + env.Dump('LIBS')


